version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: taskflow
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow
    ports: ["5432:5432"]
  backend:
    build: ./backend
    depends_on: [db]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskflow
      SPRING_DATASOURCE_USERNAME: taskflow
      SPRING_DATASOURCE_PASSWORD: taskflow
    ports: ["8080:8080"]
  frontend:
    image: node:20
    working_dir: /app
    volumes: ["./frontend-angular:/app"]
    command: sh -c "npm i && npm run start -- --host 0.0.0.0"
    ports: ["5173:5173"]
    depends_on: [backend]
